/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package darmaan;

import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.UIManager;

/**
 *
 * @author Jawad _PC
 */
public class BaseLog extends javax.swing.JFrame {

    /**
     * Creates new form BaseLog
     */
    public BaseLog() {
        initComponents();
        Caution.setVisible(false);
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/PicS/MainLogo.png")));
        setTitle("درمان");
        setResizable(false);
         UIManager.put("OptionPane.cancelButtonText","لغو");
      UIManager.put("OptionPane.okButtonText", "تایید");
      UIManager.put("OptionPane.yesButtonText", "تایید");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        userNamejTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        loginjButton1 = new javax.swing.JButton();
        forgotPassjLabel4 = new javax.swing.JLabel();
        createjLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        passjTextField2 = new javax.swing.JPasswordField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        Caution = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(597, 337));
        setResizable(false);
        getContentPane().setLayout(null);

        userNamejTextField1.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        userNamejTextField1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(userNamejTextField1);
        userNamejTextField1.setBounds(300, 100, 160, 20);

        jLabel2.setFont(new java.awt.Font("Traditional Arabic", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("نام کاربری :");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(470, 99, 60, 20);

        jLabel3.setFont(new java.awt.Font("Traditional Arabic", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("رمز کاربری :");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(470, 140, 62, 20);

        loginjButton1.setFont(new java.awt.Font("Traditional Arabic", 1, 18)); // NOI18N
        loginjButton1.setText("ورود");
        loginjButton1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        loginjButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginjButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(loginjButton1);
        loginjButton1.setBounds(400, 180, 63, 20);

        forgotPassjLabel4.setForeground(new java.awt.Color(255, 255, 255));
        forgotPassjLabel4.setText(" تان را فراموش کرده اید!");
        forgotPassjLabel4.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().add(forgotPassjLabel4);
        forgotPassjLabel4.setBounds(310, 220, 110, 14);

        createjLabel5.setForeground(new java.awt.Color(255, 255, 255));
        createjLabel5.setText("ایجاد حساب");
        createjLabel5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        createjLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                createjLabel5MouseClicked(evt);
            }
        });
        getContentPane().add(createjLabel5);
        createjLabel5.setBounds(450, 240, 60, 14);

        jLabel4.setFont(new java.awt.Font("Traditional Arabic", 1, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("ورود به سیستم");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(330, 20, 160, 56);

        passjTextField2.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        passjTextField2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        passjTextField2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                passjTextField2KeyPressed(evt);
            }
        });
        getContentPane().add(passjTextField2);
        passjTextField2.setBounds(301, 140, 160, 20);

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("گذرواژه / ");
        jLabel5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel5);
        jLabel5.setBounds(460, 220, 50, 14);

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("نام کاربری");
        jLabel6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel6);
        jLabel6.setBounds(410, 220, 50, 14);

        Caution.setFont(new java.awt.Font("Traditional Arabic", 1, 14)); // NOI18N
        Caution.setForeground(new java.awt.Color(255, 0, 0));
        Caution.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        Caution.setText("حساب کاربری قبلا ایجاد شده است!!!");
        getContentPane().add(Caution);
        Caution.setBounds(280, 240, 160, 20);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PicS/images (19).jpg"))); // NOI18N
        jLabel1.setText("گذرواژه ");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(-3, 0, 600, 337);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void createjLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_createjLabel5MouseClicked
        int a =0;
        try {
            Class.forName("org.h2.Driver");
            Connection con = DriverManager.getConnection("jdbc:h2:~/dintest", "jawad", "1234");
            
            String qury = "select * from "+Constances.TableNames.UserDetails;
            Statement pst = con.createStatement();
            ResultSet rs = pst.executeQuery(qury);
            while(rs.next()){
              a++;
            }
            
            if(a==0){
            Registeration rgs = new Registeration();
            rgs.setVisible(true);
            dispose();
            
            }else{
            Caution.setVisible(true);
            }
            
            
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(BaseLog.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(BaseLog.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_createjLabel5MouseClicked

    private void loginjButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginjButton1ActionPerformed
       String user="";
          String passwords ="";
           char [] passwo = passjTextField2.getPassword();
             String abcd = String.valueOf(passwo);  
        try {
            Class.forName("org.h2.Driver");
            Connection con = DriverManager.getConnection("jdbc:h2:~/dintest", "jawad", "1234");
            
            String qury = "select * from "+Constances.TableNames.UserDetails;
            Statement pst = con.createStatement();
            ResultSet rs = pst.executeQuery(qury);
            while(rs.next()){
            user = rs.getString(6);
            passwords =rs.getString(7);
            
             
            }
            if(user.equals(userNamejTextField1.getText())&& passwords.equals(abcd)){
            
                
                Demo dm = new Demo();
               dm.setVisible(true);
               dispose();
            
            }else{
                JOptionPane.showMessageDialog(null, "لطفا دوباره تلاش نمایید","هشدار",JOptionPane.WARNING_MESSAGE);
                userNamejTextField1.setText("");
                passjTextField2.setText("");
            }
            
            
            
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(BaseLog.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(BaseLog.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_loginjButton1ActionPerformed

    private void passjTextField2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_passjTextField2KeyPressed
           String user="";
          String passwords ="";
          char [] passwo = passjTextField2.getPassword();
             String abcd = String.valueOf(passwo);  
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
        try {
            Class.forName("org.h2.Driver");
            Connection con = DriverManager.getConnection("jdbc:h2:~/dintest", "jawad", "1234");
            
            String qury = "select * from "+Constances.TableNames.UserDetails;
            Statement pst = con.createStatement();
            ResultSet rs = pst.executeQuery(qury);
            while(rs.next()){
            user = rs.getString(6);
            passwords =rs.getString(7);
                
            }
            if(user.equals(userNamejTextField1.getText())&& passwords.equals(abcd)){
            
               Demo dm = new Demo();
               dm.setVisible(true);
               dispose();
            
            }else{
                JOptionPane.showMessageDialog(null, "لطفا دوباره تلاش نمایید","هشدار",JOptionPane.WARNING_MESSAGE);
                userNamejTextField1.setText("");
                passjTextField2.setText("");
            }
            
            
            
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(BaseLog.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(BaseLog.class.getName()).log(Level.SEVERE, null, ex);
        }
        }
    }//GEN-LAST:event_passjTextField2KeyPressed

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
       JTextField jt = new JTextField();
        String dbUserName = "";
        
        String query ="select * from "+Constances.TableNames.UserDetails;
         try {
            String userName = JOptionPane.showInputDialog(null,"لطفا نام کاربری خودرا وارد کنید                                ","",JOptionPane.INFORMATION_MESSAGE);
            Class.forName("org.h2.Driver");
            Connection con = DriverManager.getConnection("jdbc:h2:~/dintest", "jawad", "1234");
            if(con!=null){
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery(query);
            
                while(rs.next()){
                dbUserName=rs.getString(6);
                }
                if(userName.equals(dbUserName)){
                Registeration rg = new Registeration();
                rg.setVisible(true);
                dispose();
                
                }else{JOptionPane.showMessageDialog(null, "نام کاربری اشتباه می باشد!!","هشدار",JOptionPane.WARNING_MESSAGE);}
         
            
            }
            
            
            
            
            
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(BaseLog.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(BaseLog.class.getName()).log(Level.SEVERE, null, ex);
        }catch(NullPointerException ne){}
    }//GEN-LAST:event_jLabel5MouseClicked

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
        JTextField jt = new JTextField();
        String dbUserName = "";
        
        String query ="select * from "+Constances.TableNames.UserDetails;
         try {
            String userName = JOptionPane.showInputDialog(null,"لطفا گذرواژه تان را وارد کنید                                   ","",JOptionPane.INFORMATION_MESSAGE);
            Class.forName("org.h2.Driver");
            Connection con = DriverManager.getConnection("jdbc:h2:~/dintest", "jawad", "1234");
            if(con!=null){
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery(query);
            
                while(rs.next()){
                dbUserName=rs.getString(7);
                }
                if(userName.equals(dbUserName)){
                Registeration rg = new Registeration();
                rg.setVisible(true);
                dispose();
                
                }else{JOptionPane.showMessageDialog(null, "رمز کاربری اشتباه می باشد!!","هشدار",JOptionPane.WARNING_MESSAGE);}
         
            
            }
            
            
            
            
            
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(BaseLog.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(BaseLog.class.getName()).log(Level.SEVERE, null, ex);
        }catch(NullPointerException ne){}
    }//GEN-LAST:event_jLabel6MouseClicked

   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Caution;
    private javax.swing.JLabel createjLabel5;
    private javax.swing.JLabel forgotPassjLabel4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JButton loginjButton1;
    private javax.swing.JPasswordField passjTextField2;
    private javax.swing.JTextField userNamejTextField1;
    // End of variables declaration//GEN-END:variables
}
