/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package darmaan;

import darmaan.Constances;
import java.awt.Component;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JCheckBox;
import javax.swing.JOptionPane;

/**
 *
 * @author Jawad _PC
 */
public class Detailsnew extends javax.swing.JFrame {

   int totalprice =0;
    int getFirsPrice =0;
    int getSecondPrice =0;
    int getThirdPrice =0;
    int getRemain =0;
    int numb = 0;
    
    String chick_up = "Chick up";
    String implant = "Implant";
    String rct = "RCT(Root Canal Therapy)";
    String extraction = "Extraction";
    String sff = "Super Facial Filling";
    String orthodontia = "Orthodontia";
    String surgery = "Surgery";
    String scalling = "Scalling";
    String bleeching = "Bleeching";
    String diamond = "Diamond";
    String crown = "Crown";
    String veneer = "Veneer";
    String bridge = "Bridge";
   int c =0;
   int d =0;
   int e=0;
   int g =0;
   int r=0;
   int j=0;
   int n=0;
    Demo dm =  null;
    public Detailsnew(Demo dm) {
        initComponents();
         setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/PicS/MainLogo.png")));
        setTitle("درمان");
        setDefaultCloseOperation(Detailsnew.DISPOSE_ON_CLOSE);
        setResizable(false);
       this.dm=dm;
       display();
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lastnameLabel = new javax.swing.JLabel();
        dateLabel = new javax.swing.JLabel();
        detailsName = new javax.swing.JTextField();
        detailsPhone = new javax.swing.JTextField();
        firstLabel = new javax.swing.JLabel();
        detailsSecond = new javax.swing.JTextField();
        nameLabel = new javax.swing.JLabel();
        detailsPrice = new javax.swing.JTextField();
        thirdLabel = new javax.swing.JLabel();
        priceDetailsLabel = new javax.swing.JLabel();
        phoneLabel = new javax.swing.JLabel();
        detailsFirst = new javax.swing.JTextField();
        detailsLastname = new javax.swing.JTextField();
        detailsNumber = new javax.swing.JTextField();
        sickDetailsLabel = new javax.swing.JLabel();
        remainLabel = new javax.swing.JLabel();
        secondLabel = new javax.swing.JLabel();
        detailsThird = new javax.swing.JTextField();
        detailsRemain = new javax.swing.JTextField();
        priceLabel = new javax.swing.JLabel();
        saveButton1 = new javax.swing.JButton();
        numberLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        detailsSick = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        detailsAddress = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        detailsBefore = new javax.swing.JTextField();
        dateOfyear = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jCheckBox1 = new javax.swing.JCheckBox();
        jCheckBox2 = new javax.swing.JCheckBox();
        jCheckBox3 = new javax.swing.JCheckBox();
        jCheckBox4 = new javax.swing.JCheckBox();
        jCheckBox5 = new javax.swing.JCheckBox();
        jCheckBox6 = new javax.swing.JCheckBox();
        jCheckBox7 = new javax.swing.JCheckBox();
        jCheckBox8 = new javax.swing.JCheckBox();
        jCheckBox9 = new javax.swing.JCheckBox();
        jCheckBox10 = new javax.swing.JCheckBox();
        jCheckBox11 = new javax.swing.JCheckBox();
        jCheckBox12 = new javax.swing.JCheckBox();
        jCheckBox13 = new javax.swing.JCheckBox();
        jButton1 = new javax.swing.JButton();
        jCheckBox14 = new javax.swing.JCheckBox();
        jCheckBox15 = new javax.swing.JCheckBox();
        jCheckBox16 = new javax.swing.JCheckBox();
        jCheckBox17 = new javax.swing.JCheckBox();
        jCheckBox18 = new javax.swing.JCheckBox();
        jLabel3 = new javax.swing.JLabel();
        detailsFourth = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 204, 204));
        setPreferredSize(new java.awt.Dimension(1067, 650));
        getContentPane().setLayout(null);

        lastnameLabel.setFont(new java.awt.Font("Traditional Arabic", 0, 24)); // NOI18N
        lastnameLabel.setText("تخلص :");
        getContentPane().add(lastnameLabel);
        lastnameLabel.setBounds(910, 280, 80, 20);

        dateLabel.setFont(new java.awt.Font("Traditional Arabic", 0, 24)); // NOI18N
        dateLabel.setText("تاریخ :");
        getContentPane().add(dateLabel);
        dateLabel.setBounds(980, 40, 50, 30);

        detailsName.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        detailsName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                detailsNameActionPerformed(evt);
            }
        });
        getContentPane().add(detailsName);
        detailsName.setBounds(760, 240, 140, 30);

        detailsPhone.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        detailsPhone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                detailsPhoneActionPerformed(evt);
            }
        });
        getContentPane().add(detailsPhone);
        detailsPhone.setBounds(760, 400, 140, 30);

        firstLabel.setFont(new java.awt.Font("Traditional Arabic", 0, 24)); // NOI18N
        firstLabel.setText("رسید اول :");
        getContentPane().add(firstLabel);
        firstLabel.setBounds(620, 160, 90, 20);

        detailsSecond.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        detailsSecond.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                detailsSecondMouseClicked(evt);
            }
        });
        detailsSecond.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                detailsSecondActionPerformed(evt);
            }
        });
        detailsSecond.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                detailsSecondKeyPressed(evt);
            }
        });
        getContentPane().add(detailsSecond);
        detailsSecond.setBounds(470, 200, 140, 30);

        nameLabel.setFont(new java.awt.Font("Traditional Arabic", 0, 24)); // NOI18N
        nameLabel.setText("نام :");
        getContentPane().add(nameLabel);
        nameLabel.setBounds(910, 240, 50, 20);

        detailsPrice.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        detailsPrice.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                detailsPriceKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                detailsPriceKeyReleased(evt);
            }
        });
        getContentPane().add(detailsPrice);
        detailsPrice.setBounds(470, 120, 140, 30);

        thirdLabel.setFont(new java.awt.Font("Traditional Arabic", 0, 24)); // NOI18N
        thirdLabel.setText("رسید سوم :");
        getContentPane().add(thirdLabel);
        thirdLabel.setBounds(620, 240, 100, 20);

        priceDetailsLabel.setFont(new java.awt.Font("Traditional Arabic", 1, 36)); // NOI18N
        priceDetailsLabel.setText("بخش مالی");
        getContentPane().add(priceDetailsLabel);
        priceDetailsLabel.setBounds(510, 50, 120, 40);

        phoneLabel.setFont(new java.awt.Font("Traditional Arabic", 0, 24)); // NOI18N
        phoneLabel.setText("شماره تماس :");
        getContentPane().add(phoneLabel);
        phoneLabel.setBounds(910, 400, 90, 20);

        detailsFirst.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        detailsFirst.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                detailsFirstMouseClicked(evt);
            }
        });
        detailsFirst.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                detailsFirstKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                detailsFirstKeyTyped(evt);
            }
        });
        getContentPane().add(detailsFirst);
        detailsFirst.setBounds(470, 160, 140, 30);

        detailsLastname.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        getContentPane().add(detailsLastname);
        detailsLastname.setBounds(760, 280, 140, 30);

        detailsNumber.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        detailsNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                detailsNumberActionPerformed(evt);
            }
        });
        getContentPane().add(detailsNumber);
        detailsNumber.setBounds(760, 200, 140, 30);

        sickDetailsLabel.setFont(new java.awt.Font("Traditional Arabic", 1, 36)); // NOI18N
        sickDetailsLabel.setText("مشخصات مریض");
        getContentPane().add(sickDetailsLabel);
        sickDetailsLabel.setBounds(790, 110, 190, 40);

        remainLabel.setFont(new java.awt.Font("Traditional Arabic", 0, 24)); // NOI18N
        remainLabel.setText("باقیمانده :");
        getContentPane().add(remainLabel);
        remainLabel.setBounds(620, 420, 90, 20);

        secondLabel.setFont(new java.awt.Font("Traditional Arabic", 0, 24)); // NOI18N
        secondLabel.setText("رسید دوم :");
        getContentPane().add(secondLabel);
        secondLabel.setBounds(620, 200, 110, 20);

        detailsThird.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        detailsThird.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                detailsThirdMouseClicked(evt);
            }
        });
        detailsThird.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                detailsThirdActionPerformed(evt);
            }
        });
        detailsThird.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                detailsThirdKeyPressed(evt);
            }
        });
        getContentPane().add(detailsThird);
        detailsThird.setBounds(470, 240, 140, 30);

        detailsRemain.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        detailsRemain.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                detailsRemainActionPerformed(evt);
            }
        });
        getContentPane().add(detailsRemain);
        detailsRemain.setBounds(470, 420, 140, 30);

        priceLabel.setFont(new java.awt.Font("Traditional Arabic", 0, 24)); // NOI18N
        priceLabel.setText("قیمت کل:");
        getContentPane().add(priceLabel);
        priceLabel.setBounds(620, 120, 100, 20);

        saveButton1.setFont(new java.awt.Font("Traditional Arabic", 1, 18)); // NOI18N
        saveButton1.setText("ذخیره");
        saveButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(saveButton1);
        saveButton1.setBounds(640, 510, 90, 30);

        numberLabel.setFont(new java.awt.Font("Traditional Arabic", 0, 24)); // NOI18N
        numberLabel.setText("نمبر مشخصه :");
        getContentPane().add(numberLabel);
        numberLabel.setBounds(910, 200, 118, 20);

        detailsSick.setBackground(new java.awt.Color(204, 255, 255));
        detailsSick.setColumns(20);
        detailsSick.setRows(5);
        detailsSick.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "انتخاب شده ها", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Traditional Arabic", 1, 16))); // NOI18N
        jScrollPane1.setViewportView(detailsSick);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(0, 0, 200, 600);

        jLabel1.setFont(new java.awt.Font("Traditional Arabic", 0, 24)); // NOI18N
        jLabel1.setText("آدرس :");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(910, 350, 130, 32);

        detailsAddress.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        detailsAddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                detailsAddressActionPerformed(evt);
            }
        });
        getContentPane().add(detailsAddress);
        detailsAddress.setBounds(760, 360, 140, 30);

        jLabel4.setFont(new java.awt.Font("Traditional Arabic", 0, 24)); // NOI18N
        jLabel4.setText("مریضی قبلی :");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(910, 320, 90, 20);

        detailsBefore.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        getContentPane().add(detailsBefore);
        detailsBefore.setBounds(760, 320, 140, 30);

        dateOfyear.setFont(new java.awt.Font("Traditional Arabic", 0, 24)); // NOI18N
        dateOfyear.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        dateOfyear.setText("۱۳۹۹/۲/۲۳");
        getContentPane().add(dateOfyear);
        dateOfyear.setBounds(830, 40, 130, 30);

        jPanel1.setBackground(new java.awt.Color(204, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "انواع تداوی", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Traditional Arabic", 1, 16))); // NOI18N

        jCheckBox1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jCheckBox1.setText("Chick up");
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });

        jCheckBox2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jCheckBox2.setText("Implant");
        jCheckBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox2ActionPerformed(evt);
            }
        });

        jCheckBox3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jCheckBox3.setText("RCT(Root Canal Therapy)");
        jCheckBox3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox3ActionPerformed(evt);
            }
        });

        jCheckBox4.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jCheckBox4.setText("Super Facial Filling");
        jCheckBox4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox4ActionPerformed(evt);
            }
        });

        jCheckBox5.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jCheckBox5.setText("Extraction");

        jCheckBox6.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jCheckBox6.setText("Orthodontia");
        jCheckBox6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox6ActionPerformed(evt);
            }
        });

        jCheckBox7.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jCheckBox7.setText("Surgery");

        jCheckBox8.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jCheckBox8.setText("Scalling");

        jCheckBox9.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jCheckBox9.setText("Bleeching");
        jCheckBox9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox9ActionPerformed(evt);
            }
        });

        jCheckBox10.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jCheckBox10.setText("Diamond");
        jCheckBox10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox10ActionPerformed(evt);
            }
        });

        jCheckBox11.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jCheckBox11.setText("Crown");
        jCheckBox11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox11ActionPerformed(evt);
            }
        });

        jCheckBox12.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jCheckBox12.setText("Veneer");

        jCheckBox13.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jCheckBox13.setText("Bridge");
        jCheckBox13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox13ActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Traditional Arabic", 1, 18)); // NOI18N
        jButton1.setText("انتخاب");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jCheckBox14.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jCheckBox14.setText("Drug");

        jCheckBox15.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jCheckBox15.setText("C.Denture");
        jCheckBox15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox15ActionPerformed(evt);
            }
        });

        jCheckBox16.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jCheckBox16.setText("P.Denture");
        jCheckBox16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox16ActionPerformed(evt);
            }
        });

        jCheckBox17.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jCheckBox17.setText("Space Retainer");

        jCheckBox18.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jCheckBox18.setText("Aesthetics");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jCheckBox1)
                    .addComponent(jCheckBox12, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCheckBox11, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCheckBox9)
                    .addComponent(jCheckBox8)
                    .addComponent(jCheckBox10)
                    .addComponent(jCheckBox7)
                    .addComponent(jCheckBox6)
                    .addComponent(jCheckBox4)
                    .addComponent(jCheckBox5)
                    .addComponent(jCheckBox2)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jCheckBox18)
                        .addGap(45, 45, 45)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jCheckBox3)
                    .addComponent(jCheckBox14)
                    .addComponent(jCheckBox15)
                    .addComponent(jCheckBox16)
                    .addComponent(jCheckBox13, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCheckBox17))
                .addGap(102, 102, 102))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jCheckBox1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckBox2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckBox3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckBox5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckBox4)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jCheckBox6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jCheckBox7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jCheckBox8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jCheckBox9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jCheckBox10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jCheckBox11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jCheckBox12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jCheckBox13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jCheckBox14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jCheckBox15)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jCheckBox16)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jCheckBox17)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jCheckBox18)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(200, 0, 260, 600);

        jLabel3.setFont(new java.awt.Font("Traditional Arabic", 0, 24)); // NOI18N
        jLabel3.setText("رسید چهارم :");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(620, 280, 90, 30);

        detailsFourth.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        detailsFourth.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                detailsFourthKeyPressed(evt);
            }
        });
        getContentPane().add(detailsFourth);
        detailsFourth.setBounds(470, 280, 140, 30);

        jButton2.setFont(new java.awt.Font("Traditional Arabic", 1, 18)); // NOI18N
        jButton2.setText("تازه سازی");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(513, 510, 90, 30);

        jLabel5.setFont(new java.awt.Font("Traditional Arabic", 0, 24)); // NOI18N
        jLabel5.setText("رسید پنجم :");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(620, 330, 80, 30);

        jLabel6.setFont(new java.awt.Font("Traditional Arabic", 0, 24)); // NOI18N
        jLabel6.setText("رسید ششم :");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(620, 370, 90, 30);

        jTextField5.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextField5.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField5KeyPressed(evt);
            }
        });
        getContentPane().add(jTextField5);
        jTextField5.setBounds(470, 330, 140, 30);

        jTextField6.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextField6.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField6KeyPressed(evt);
            }
        });
        getContentPane().add(jTextField6);
        jTextField6.setBounds(470, 370, 140, 30);

        jLabel2.setBackground(new java.awt.Color(204, 204, 204));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PicS/bbggbt.png"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 0, 1050, 650);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void detailsNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_detailsNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_detailsNameActionPerformed

    private void detailsThirdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_detailsThirdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_detailsThirdActionPerformed

    private void detailsPhoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_detailsPhoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_detailsPhoneActionPerformed

    private void detailsRemainActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_detailsRemainActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_detailsRemainActionPerformed

    private void saveButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButton1ActionPerformed
Object ob [] = {"تایید","لغو"};

int num = JOptionPane.showOptionDialog(null, "تغببرات ذخیره گردد!!", "پیام تاییدی", JOptionPane.OK_CANCEL_OPTION,JOptionPane.INFORMATION_MESSAGE,null,ob,ob[0]);

  if(num == 0){
                         
                        try {
            Class.forName("org.h2.Driver");
            
            String query = "update "+Constances.TableNames.SickDetails+" set "+Constances.SickDetails.NAME+" = '"+detailsName.getText()+"' ,"+Constances.SickDetails.LAST_NAME+" = '"+detailsLastname.getText()+"' ,"+Constances.SickDetails.PHONE_NUMBER+" = '"+detailsPhone.getText()+"' ,"
                    +Constances.SickDetails.FIRST_RECIEVE+" = '"+detailsFirst.getText()+"' , "+
                          Constances.SickDetails.SECOND_RECIEVE+" = '"+detailsSecond.getText()+" ',"+Constances.SickDetails.THIRD_RECIEVE+" = '"+detailsThird.getText()+
                    "',"+Constances.SickDetails.REMAIN+" ='"+detailsRemain.getText()+" ',"+Constances.SickDetails.KIND_SICK+" ='"+detailsSick.getText()+"' ,"+Constances.SickDetails.ADDRESS+" = '"+detailsAddress.getText()+"' ,"+Constances.SickDetails.BEFORE_SICK+" = '"+detailsBefore.getText()+"' ,"+Constances.SickDetails.FOURTH_RECIEVE+" = '"+detailsFourth.getText()
                    +"' ,"+Constances.SickDetails.FIFTH_RECIEVE+" = '"+jTextField5.getText()+"' ,"+Constances.SickDetails.SIXTH_RECIEVE+" = '"+jTextField6.getText()
                    +"' ,"+Constances.SickDetails.TOTAL_PRICE+" = '"+detailsPrice.getText()+"'where "+Constances.SickDetails.Number+" = '"+detailsNumber.getText()+"'";
            Connection con = DriverManager.getConnection("jdbc:h2:~/dintest","jawad","1234");
            if(con!=null){
                Statement st = con.createStatement();
                int result =st.executeUpdate(query);
                
                if(result != 0){
                    Object ob1 [] = {"تایید"};
                    JOptionPane.showOptionDialog(null, "تغببرات موفقانه ذخیره گردید","پیام تاییدی",JOptionPane.OK_OPTION,JOptionPane.INFORMATION_MESSAGE,null,ob1,ob1[0]);
                  //   SicksList sl  = new SicksList();
                    // sl.disp();
                    dm.disp();
                      dispose();
      //  SicksList lst = new SicksList();
       // lst.setVisible(true);
                }
            }
            
            
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Demo.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(Demo.class.getName()).log(Level.SEVERE, null, ex);
        } 
                   
                    }  
                else{
                
                }


        // TODO add your handling code here:
    }//GEN-LAST:event_saveButton1ActionPerformed

    private void detailsPriceKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_detailsPriceKeyPressed
       
        
        
         
    }//GEN-LAST:event_detailsPriceKeyPressed

    private void detailsFirstKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_detailsFirstKeyPressed
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            if(detailsFirst.getText().trim().isEmpty()){
                c=0;
            }else{
            
                if(c==0){
         try {
        int remain = Integer.parseInt(detailsRemain.getText().trim());
        int first = Integer.parseInt(detailsFirst.getText().trim());
       int  mainRemain = remain-first;
        detailsRemain.setText(mainRemain+"");
        detailsFirst.setEditable(false);
       }catch(NumberFormatException nfe){}
           c++; 
            }else{}
            
            }
            
        
        }
    }//GEN-LAST:event_detailsFirstKeyPressed

    private void detailsThirdKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_detailsThirdKeyPressed
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            if(detailsThird.getText().trim().isEmpty()){
                e=0;
            }else{
            
                if(e==0){
         try {
        int remain = Integer.parseInt(detailsRemain.getText().trim());
        int first = Integer.parseInt(detailsThird.getText().trim());
       int  mainRemain = remain-first;
       if(mainRemain<0){
       JOptionPane.showConfirmDialog(null, "مبلغ زیادی وارد کرده اید!!", "هشدار", JOptionPane.WARNING_MESSAGE);
       e=0;
       }else{
        detailsRemain.setText(mainRemain+"");
        detailsThird.setEditable(false);
       e++;
       }
       
       }catch(NumberFormatException nfe){}
            
            }else{}
            
            }
            
        
        }
        
    }//GEN-LAST:event_detailsThirdKeyPressed

    private void detailsFirstMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_detailsFirstMouseClicked
      
    }//GEN-LAST:event_detailsFirstMouseClicked

    private void detailsThirdMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_detailsThirdMouseClicked
      
    }//GEN-LAST:event_detailsThirdMouseClicked

    private void detailsFirstKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_detailsFirstKeyTyped
      
    }//GEN-LAST:event_detailsFirstKeyTyped

    private void detailsSecondKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_detailsSecondKeyPressed
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            if(detailsSecond.getText().trim().isEmpty()){
                d=0;
            }else{
            
                if(d==0){
         try {
        int remain = Integer.parseInt(detailsRemain.getText().trim());
        int first = Integer.parseInt(detailsSecond.getText().trim());
       int  mainRemain = remain-first;
       if(mainRemain<0){
       JOptionPane.showConfirmDialog(null, "مبلغ زیادی وارد کرده اید!!", "هشدار", JOptionPane.WARNING_MESSAGE);
       d=0;
       }else{
        detailsRemain.setText(mainRemain+"");
        detailsSecond.setEditable(false);
       d++;
       }
       }catch(NumberFormatException nfe){}
            
            }else{}
            
            }
            
        
        }
    }//GEN-LAST:event_detailsSecondKeyPressed

    private void detailsSecondMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_detailsSecondMouseClicked

    }//GEN-LAST:event_detailsSecondMouseClicked

    private void detailsSecondActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_detailsSecondActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_detailsSecondActionPerformed

    private void detailsNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_detailsNumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_detailsNumberActionPerformed

    private void detailsAddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_detailsAddressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_detailsAddressActionPerformed

    private void jCheckBox11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox11ActionPerformed

    private void jCheckBox9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox9ActionPerformed

    private void jCheckBox10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox10ActionPerformed

    private void jCheckBox6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox6ActionPerformed

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox1ActionPerformed

    private void jCheckBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String temp = "";
        String concat= detailsSick.getText();     
        String result = "";
        for(Component c: jPanel1.getComponents()){
        if(c.getClass().equals(JCheckBox.class)){
        JCheckBox jck = (JCheckBox)c;
        if(jck.isSelected()){
        result += jck.getText()+" , \n\n";
        }
        temp = concat.concat(result);
        } 
        detailsSick.setText(temp);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jCheckBox3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox3ActionPerformed

    private void jCheckBox4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox4ActionPerformed

    private void jCheckBox13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox13ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox13ActionPerformed

    private void jCheckBox15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox15ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox15ActionPerformed

    private void jCheckBox16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox16ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox16ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        display();
            jCheckBox1.setSelected(false);
            jCheckBox2.setSelected(false);
            jCheckBox3.setSelected(false);
            jCheckBox4.setSelected(false);
            jCheckBox5.setSelected(false);
            jCheckBox6.setSelected(false);
            jCheckBox7.setSelected(false);
            jCheckBox8.setSelected(false);
            jCheckBox9.setSelected(false);
            jCheckBox10.setSelected(false);
            jCheckBox11.setSelected(false);
            jCheckBox12.setSelected(false);
            jCheckBox13.setSelected(false);
            jCheckBox14.setSelected(false);
            jCheckBox15.setSelected(false);
            jCheckBox16.setSelected(false);
            jCheckBox17.setSelected(false);
            jCheckBox18.setSelected(false);
            detailsSick.setText("");
        detailsSecond.setEditable(true);
        d=0;
        detailsThird.setEditable(true);
        e=0;
        detailsFourth.setEditable(true);
        g=0;
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void detailsFourthKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_detailsFourthKeyPressed
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            if(detailsFourth.getText().trim().isEmpty()){
                g=0;
            }else{
            
                if(g==0){
         try {
        int remain = Integer.parseInt(detailsRemain.getText().trim());
        int first = Integer.parseInt(detailsFourth.getText().trim());
       int  mainRemain = remain-first;
       if(mainRemain<0){
       JOptionPane.showConfirmDialog(null, "مبلغ زیادی وارد کرده اید!!", "هشدار", JOptionPane.WARNING_MESSAGE);
       g=0;
       }else{
        detailsRemain.setText(mainRemain+"");
        detailsFourth.setEditable(false);
       g++; 
       }
       
       }catch(NumberFormatException nfe){}
           
            }else{}
            
            }
            
        
        }
    }//GEN-LAST:event_detailsFourthKeyPressed

    private void detailsPriceKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_detailsPriceKeyReleased
      detailsRemain.setText(detailsPrice.getText());
      
    }//GEN-LAST:event_detailsPriceKeyReleased

    private void jTextField5KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField5KeyPressed
         if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            if(jTextField5.getText().trim().isEmpty()){
                j=0;
            }else{
            
                if(j==0){
         try {
        int remain = Integer.parseInt(detailsRemain.getText().trim());
        int first = Integer.parseInt(jTextField5.getText().trim());
       int  mainRemain = remain-first;
       if(mainRemain<0){
       JOptionPane.showConfirmDialog(null, "مبلغ زیادی وارد کرده اید!!", "هشدار", JOptionPane.WARNING_MESSAGE);
       j=0;
       }else{
        detailsRemain.setText(mainRemain+"");
        detailsFourth.setEditable(false);
       j++; 
       }
       
       }catch(NumberFormatException nfe){}
           
            }else{}
            
            }
            
        
        }
    }//GEN-LAST:event_jTextField5KeyPressed

    private void jTextField6KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField6KeyPressed
         if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            if(jTextField6.getText().trim().isEmpty()){
                n=0;
            }else{
            
                if(n==0){
         try {
        int remain = Integer.parseInt(detailsRemain.getText().trim());
        int first = Integer.parseInt(jTextField6.getText().trim());
       int  mainRemain = remain-first;
       if(mainRemain<0){
       JOptionPane.showConfirmDialog(null, "مبلغ زیادی وارد کرده اید!!", "هشدار", JOptionPane.WARNING_MESSAGE);
       n=0;
       }else{
        detailsRemain.setText(mainRemain+"");
        detailsFourth.setEditable(false);
       n++; 
       }
       
       }catch(NumberFormatException nfe){}
           
            }else{}
            
            }
            
        
        }
    }//GEN-LAST:event_jTextField6KeyPressed

    /**
     * @param args the command line arguments
     */
    public void display() {
        
       String personId = dm.personId;
       String query ="select * from "+Constances.TableNames.SickDetails+" where "+Constances.SickDetails.Number+" = '"+personId+"'";
        
        try {
            Class.forName("org.h2.Driver");
            Connection con = DriverManager.getConnection("jdbc:h2:~/dintest", "jawad", "1234");
            if(con!=null){
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery(query);
            
                while(rs.next()){
             detailsNumber.setText(rs.getString(2));
             detailsName.setText(rs.getString(3));
             detailsLastname.setText(rs.getString(4));
             detailsBefore.setText(rs.getString(6));
             detailsAddress.setText(rs.getString(16));
             detailsPhone.setText(rs.getString(7));
             detailsPrice.setText(rs.getString(9));
             detailsFirst.setText(rs.getString(10));
             detailsSecond.setText(rs.getString(11));
             detailsThird.setText(rs.getString(12));
             detailsFourth.setText(rs.getString(17));
             detailsRemain.setText(rs.getString(13));
             jTextField5.setText(rs.getString(18));
             jTextField6.setText(rs.getString(19));
             ShamsiDate sd = new ShamsiDate();
             dateOfyear.setText(sd.getCurrentShamsidate());
             detailsSick.setText(rs.getString(8));
                    
                 
                }
             
  }
        } catch (ClassNotFoundException ex) {
          Logger.getLogger(Demo.class.getName()).log(Level.SEVERE, null, ex);
      } catch (SQLException ex) {
          Logger.getLogger(Demo.class.getName()).log(Level.SEVERE, null, ex);
      }
    }

    void disab(){
    
//         r = Integer.parseInt(detailsRemain.getText().trim());
//       
//       if(detailsFirst.getText().trim().isEmpty()||r==0){
//       detailsFirst.setEditable(false);
//       detailsSecond.setEditable(false);
//       detailsThird.setEditable(false);
//       detailsFourth.setEditable(false);
//       detailsRemain.setEditable(false);
//       }
//        else{detailsFirst.setEditable(false);}
//    
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel dateLabel;
    private javax.swing.JLabel dateOfyear;
    private javax.swing.JTextField detailsAddress;
    private javax.swing.JTextField detailsBefore;
    private javax.swing.JTextField detailsFirst;
    private javax.swing.JTextField detailsFourth;
    private javax.swing.JTextField detailsLastname;
    private javax.swing.JTextField detailsName;
    private javax.swing.JTextField detailsNumber;
    private javax.swing.JTextField detailsPhone;
    private javax.swing.JTextField detailsPrice;
    private javax.swing.JTextField detailsRemain;
    private javax.swing.JTextField detailsSecond;
    private javax.swing.JTextArea detailsSick;
    private javax.swing.JTextField detailsThird;
    private javax.swing.JLabel firstLabel;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox10;
    private javax.swing.JCheckBox jCheckBox11;
    private javax.swing.JCheckBox jCheckBox12;
    private javax.swing.JCheckBox jCheckBox13;
    private javax.swing.JCheckBox jCheckBox14;
    private javax.swing.JCheckBox jCheckBox15;
    private javax.swing.JCheckBox jCheckBox16;
    private javax.swing.JCheckBox jCheckBox17;
    private javax.swing.JCheckBox jCheckBox18;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JCheckBox jCheckBox3;
    private javax.swing.JCheckBox jCheckBox4;
    private javax.swing.JCheckBox jCheckBox5;
    private javax.swing.JCheckBox jCheckBox6;
    private javax.swing.JCheckBox jCheckBox7;
    private javax.swing.JCheckBox jCheckBox8;
    private javax.swing.JCheckBox jCheckBox9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JLabel lastnameLabel;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JLabel numberLabel;
    private javax.swing.JLabel phoneLabel;
    private javax.swing.JLabel priceDetailsLabel;
    private javax.swing.JLabel priceLabel;
    private javax.swing.JLabel remainLabel;
    private javax.swing.JButton saveButton1;
    private javax.swing.JLabel secondLabel;
    private javax.swing.JLabel sickDetailsLabel;
    private javax.swing.JLabel thirdLabel;
    // End of variables declaration//GEN-END:variables
}
