/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package darmaan;

import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import org.h2.jdbc.JdbcSQLIntegrityConstraintViolationException;

/**
 *
 * @author Jawad _PC
 */
public class NewJFrame extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    
    
    public NewJFrame() {
        initComponents();
         setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/PicS/MainLogo.png")));
        setTitle("درمان");
        setResizable(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 153, 255));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Traditional Arabic", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText("را وارد نمایید!!");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(120, 230, 120, 30);

        jTextField1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField1KeyPressed(evt);
            }
        });
        jPanel1.add(jTextField1);
        jTextField1.setBounds(120, 270, 250, 40);

        jLabel3.setFont(new java.awt.Font("Traditional Arabic", 1, 16)); // NOI18N
        jLabel3.setText("Licence Key");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(250, 234, 120, 26);

        jButton1.setFont(new java.awt.Font("Traditional Arabic", 1, 16)); // NOI18N
        jButton1.setText("تایید");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(210, 320, 51, 35);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PicS/IMG_3784.JPG"))); // NOI18N
        jPanel1.add(jLabel2);
        jLabel2.setBounds(0, 0, 500, 400);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 498, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        CheckUp();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextField1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyPressed
       if(evt.getKeyCode()==KeyEvent.VK_ENTER){
       CheckUp();
       }
    }//GEN-LAST:event_jTextField1KeyPressed

    
    public void CheckUp(){
     Demo dm = new Demo();
     BaseLog bs = new BaseLog();
     if(dm.countRows()==0){
      
                 
                    
                       if(jTextField1.getText().trim().isEmpty()){
                       
                           JOptionPane.showMessageDialog(null, "لطفا با مدیرعامل برنامه به تماس شوید!!","هشدار",JOptionPane.OK_OPTION);
                       
                       } else{
                        try {
                             int a = Integer.parseInt(jTextField1.getText());
            Class.forName("org.h2.Driver");
            String teethQury = "insert into "+Constances.TableNames.CHICK+"(jen)values('"+jTextField1.getText().trim()+"')";
           
            Connection con = DriverManager.getConnection("jdbc:h2:~/dintest","jawad","1234");
            if(con!=null){
                Statement st = con.createStatement();
                int result =st.executeUpdate(teethQury);
                
                if(result != 0){
                    JOptionPane.showMessageDialog(null, "به برنامه درمان خوش آمدید!!","", JOptionPane.INFORMATION_MESSAGE);
                    dispose();
                    bs.setVisible(true);
                }
            }
            
            
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Demo.class.getName()).log(Level.SEVERE, null, ex);
        }catch(JdbcSQLIntegrityConstraintViolationException exc){
       
        }catch (SQLException ex) {
            Logger.getLogger(Demo.class.getName()).log(Level.SEVERE, null, ex);
        }catch (NumberFormatException e){
      JOptionPane.showMessageDialog(null, "لطفا با مدیرعامل برنامه به تماس شوید!!","هشدار",JOptionPane.OK_OPTION);
      }
                       }       
        
     }else{
        try {
             Class.forName("org.h2.Driver");
            Connection con = DriverManager.getConnection("jdbc:h2:~/dintest", "jawad", "1234");
            
             int personId = Integer.parseInt(jTextField1.getText().trim());
     int jen = 0;
     int temp=0;
       String query ="select * from "+Constances.TableNames.CHICK;
       
            
           
            if(con!=null){
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery(query);
            
                while(rs.next()){
             jen = Integer.parseInt(rs.getString(1)); 
                 
                }
                if(personId==jen){
                    dispose();
                    dm.setVisible(true);
                    temp = personId*219/213+146;
                     String teethQury = "insert into "+Constances.TableNames.CHICK+"(jen)values('"+temp+"')";
                    st.execute(teethQury);
                }else{
               JOptionPane.showMessageDialog(null, "لطفا با مدیرعامل برنامه به تماس شوید!!","هشدار",JOptionPane.OK_OPTION);
                }
             
  }
        } catch (ClassNotFoundException ex) {
          Logger.getLogger(Demo.class.getName()).log(Level.SEVERE, null, ex);
      } catch (SQLException ex) {
          Logger.getLogger(Demo.class.getName()).log(Level.SEVERE, null, ex);
      }catch (NumberFormatException e){
      JOptionPane.showMessageDialog(null, "لطفا با مدیرعامل برنامه به تماس شوید!!","هشدار",JOptionPane.OK_OPTION);
      }
     
     
     
     
     
     }  
    
    
    
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
