/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package darmaan;

import java.awt.Component;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JCheckBox;
import javax.swing.JOptionPane;
import javax.swing.UIManager;

/**
 *
 * @author Jawad _PC
 */
public class TeethDetails extends javax.swing.JFrame {

    /**
     * Creates new form TeethDetails
     */
    ShamsiDate dt = new ShamsiDate();
    int a =0;
    String personId;
    Demo dm =  null;
    public TeethDetails(Demo dm) {
        initComponents();
         setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/PicS/MainLogo.png")));
        setTitle("درمان");
        this.dm=dm;
        
        setDefaultCloseOperation(TeethDetails.DISPOSE_ON_CLOSE);
        date1.setText(dt.getCurrentShamsidate());
        date2.setText(dt.getCurrentShamsidate());
        date3.setText(dt.getCurrentShamsidate());
        date4.setText(dt.getCurrentShamsidate());
        date5.setText(dt.getCurrentShamsidate());
        date6.setText(dt.getCurrentShamsidate());
      UIManager.put("OptionPane.cancelButtonText","لغو");
      UIManager.put("OptionPane.okButtonText", "تایید");
      UIManager.put("OptionPane.yesButtonText", "تایید");
      jTextField8.setEditable(false);
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTextField8 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        CheckBox1 = new javax.swing.JCheckBox();
        CheckBox8 = new javax.swing.JCheckBox();
        CheckBox2 = new javax.swing.JCheckBox();
        CheckBox7 = new javax.swing.JCheckBox();
        CheckBox3 = new javax.swing.JCheckBox();
        CheckBox6 = new javax.swing.JCheckBox();
        CheckBox4 = new javax.swing.JCheckBox();
        CheckBox5 = new javax.swing.JCheckBox();
        jCheckBox9 = new javax.swing.JCheckBox();
        jCheckBox10 = new javax.swing.JCheckBox();
        jCheckBox11 = new javax.swing.JCheckBox();
        jCheckBox12 = new javax.swing.JCheckBox();
        jCheckBox13 = new javax.swing.JCheckBox();
        jCheckBox14 = new javax.swing.JCheckBox();
        jCheckBox15 = new javax.swing.JCheckBox();
        jCheckBox16 = new javax.swing.JCheckBox();
        jCheckBox17a = new javax.swing.JCheckBox();
        jCheckBox18b = new javax.swing.JCheckBox();
        jCheckBox19e = new javax.swing.JCheckBox();
        jCheckBox20c = new javax.swing.JCheckBox();
        jCheckBox21f = new javax.swing.JCheckBox();
        jCheckBox22g = new javax.swing.JCheckBox();
        jCheckBox23d = new javax.swing.JCheckBox();
        jCheckBox24h = new javax.swing.JCheckBox();
        jCheckBox25 = new javax.swing.JCheckBox();
        jCheckBox26 = new javax.swing.JCheckBox();
        jCheckBox27 = new javax.swing.JCheckBox();
        jCheckBox28 = new javax.swing.JCheckBox();
        jCheckBox29 = new javax.swing.JCheckBox();
        jCheckBox30 = new javax.swing.JCheckBox();
        jCheckBox31 = new javax.swing.JCheckBox();
        jCheckBox32 = new javax.swing.JCheckBox();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        date1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        date2 = new javax.swing.JLabel();
        date3 = new javax.swing.JLabel();
        date4 = new javax.swing.JLabel();
        date5 = new javax.swing.JLabel();
        date6 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(153, 153, 153));
        setPreferredSize(new java.awt.Dimension(990, 700));
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Traditional Arabic", 1, 36)); // NOI18N
        jLabel1.setText("مشخصات دندان را وارد نمایید");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(310, 20, 316, 30);

        jTextField8.setFont(new java.awt.Font("Traditional Arabic", 1, 14)); // NOI18N
        jTextField8.setText("نمبر مشخصه را وارد نمایید");
        jTextField8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextField8MouseClicked(evt);
            }
        });
        jTextField8.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField8KeyPressed(evt);
            }
        });
        getContentPane().add(jTextField8);
        jTextField8.setBounds(700, 20, 110, 27);

        jLabel11.setFont(new java.awt.Font("Traditional Arabic", 1, 18)); // NOI18N
        jLabel11.setText("جستجو :");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(810, 20, 52, 29);

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PicS/sea.png"))); // NOI18N
        getContentPane().add(jLabel12);
        jLabel12.setBounds(870, 20, 39, 39);

        jButton1.setFont(new java.awt.Font("Traditional Arabic", 1, 18)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PicS/saveIcon.png"))); // NOI18N
        jButton1.setText("ثبت");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(760, 620, 91, 40);

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        CheckBox1.setText("1");
        CheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CheckBox1ActionPerformed(evt);
            }
        });

        CheckBox8.setText("8");

        CheckBox2.setText("2");

        CheckBox7.setText("7");

        CheckBox3.setText("3");
        CheckBox3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CheckBox3ActionPerformed(evt);
            }
        });

        CheckBox6.setText("6");

        CheckBox4.setText("4");

        CheckBox5.setText("5");

        jCheckBox9.setText("1");

        jCheckBox10.setText("2");

        jCheckBox11.setText("3");

        jCheckBox12.setText("4");

        jCheckBox13.setText("5");

        jCheckBox14.setText("6");

        jCheckBox15.setText("7");

        jCheckBox16.setText("8");

        jCheckBox17a.setText("1");

        jCheckBox18b.setText("2");

        jCheckBox19e.setText("5");

        jCheckBox20c.setText("3");

        jCheckBox21f.setText("6");

        jCheckBox22g.setText("7");

        jCheckBox23d.setText("4");

        jCheckBox24h.setText("8");

        jCheckBox25.setText("1");

        jCheckBox26.setText("2");
        jCheckBox26.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox26ActionPerformed(evt);
            }
        });

        jCheckBox27.setText("3");
        jCheckBox27.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox27ActionPerformed(evt);
            }
        });

        jCheckBox28.setText("4");
        jCheckBox28.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox28ActionPerformed(evt);
            }
        });

        jCheckBox29.setText("5");

        jCheckBox30.setText("6");

        jCheckBox31.setText("7");

        jCheckBox32.setText("8");

        jLabel7.setFont(new java.awt.Font("Traditional Arabic", 1, 18)); // NOI18N
        jLabel7.setText("فک بالا سمت راست :");

        jLabel9.setFont(new java.awt.Font("Traditional Arabic", 1, 18)); // NOI18N
        jLabel9.setText("فک پایین سمت راست :");

        jLabel22.setFont(new java.awt.Font("Traditional Arabic", 1, 18)); // NOI18N
        jLabel22.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel22.setText(": فک بالا سمت چپ");

        jLabel23.setFont(new java.awt.Font("Traditional Arabic", 1, 18)); // NOI18N
        jLabel23.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel23.setText(": فک پایین سمت چپ");

        jButton3.setFont(new java.awt.Font("Traditional Arabic", 1, 18)); // NOI18N
        jButton3.setText("انتخاب");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel22, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jCheckBox24h))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel23, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jCheckBox32)))
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jCheckBox22g, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jCheckBox31, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jCheckBox30)
                    .addComponent(jCheckBox21f))
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jCheckBox19e, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jCheckBox29, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jCheckBox23d, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jCheckBox28, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jCheckBox20c)
                    .addComponent(jCheckBox27))
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jCheckBox18b, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jCheckBox26, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jCheckBox17a, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jCheckBox25, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(CheckBox1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jCheckBox9))
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(CheckBox2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jCheckBox10))
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(CheckBox3, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jCheckBox11, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(CheckBox4, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jCheckBox12, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(CheckBox5, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jCheckBox13, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(CheckBox6, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jCheckBox14, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(CheckBox7, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jCheckBox15, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(CheckBox8, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jCheckBox16, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, 118, Short.MAX_VALUE))
                .addContainerGap())
            .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(CheckBox1)
                                    .addComponent(CheckBox2)
                                    .addComponent(CheckBox3)
                                    .addComponent(CheckBox4)
                                    .addComponent(CheckBox5)
                                    .addComponent(CheckBox6)
                                    .addComponent(CheckBox7)
                                    .addComponent(CheckBox8)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(34, 34, 34)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jCheckBox9)
                                    .addComponent(jCheckBox10)
                                    .addComponent(jCheckBox11)
                                    .addComponent(jCheckBox12)
                                    .addComponent(jCheckBox13)
                                    .addComponent(jCheckBox14)
                                    .addComponent(jCheckBox15)
                                    .addComponent(jCheckBox16)
                                    .addComponent(jLabel9)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jCheckBox17a)
                                        .addComponent(jCheckBox18b)
                                        .addComponent(jCheckBox20c)
                                        .addComponent(jCheckBox23d))
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jCheckBox24h)
                                        .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jCheckBox22g)
                                        .addComponent(jCheckBox21f)
                                        .addComponent(jCheckBox19e)))
                                .addGap(33, 33, 33)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jCheckBox25)
                                    .addComponent(jCheckBox32)
                                    .addComponent(jLabel23)
                                    .addComponent(jCheckBox26)
                                    .addComponent(jCheckBox27)
                                    .addComponent(jCheckBox28)
                                    .addComponent(jCheckBox29)
                                    .addComponent(jCheckBox30)
                                    .addComponent(jCheckBox31))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(20, 80, 930, 130);

        jPanel3.setBackground(new java.awt.Color(102, 102, 102));

        jLabel2.setFont(new java.awt.Font("Traditional Arabic", 1, 30)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("جلسات");
        jLabel2.setToolTipText("");

        jLabel3.setFont(new java.awt.Font("Traditional Arabic", 1, 30)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("تاریخ");

        jLabel4.setFont(new java.awt.Font("Traditional Arabic", 1, 30)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("تشریحات");
        jLabel4.setToolTipText("");

        jLabel5.setFont(new java.awt.Font("Traditional Arabic", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("اول");

        date1.setForeground(new java.awt.Color(255, 255, 255));
        date1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        date1.setText("jLabel6");
        date1.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(153, 153, 153)));

        jTextField1.setBackground(new java.awt.Color(102, 102, 102));
        jTextField1.setFont(new java.awt.Font("Traditional Arabic", 1, 16)); // NOI18N
        jTextField1.setForeground(new java.awt.Color(255, 255, 255));
        jTextField1.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel8.setFont(new java.awt.Font("Traditional Arabic", 1, 30)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("موقعیت دندان");

        jLabel13.setFont(new java.awt.Font("Traditional Arabic", 1, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("دوم");

        jLabel14.setFont(new java.awt.Font("Traditional Arabic", 1, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("سوم");

        jLabel15.setFont(new java.awt.Font("Traditional Arabic", 1, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("چهارم");

        jLabel16.setFont(new java.awt.Font("Traditional Arabic", 1, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setText("پنجم");

        jLabel17.setFont(new java.awt.Font("Traditional Arabic", 1, 18)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setText("ششم");

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));

        jTextArea1.setBackground(new java.awt.Color(102, 102, 102));
        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Traditional Arabic", 1, 18)); // NOI18N
        jTextArea1.setForeground(new java.awt.Color(255, 255, 255));
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        date2.setForeground(new java.awt.Color(255, 255, 255));
        date2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        date2.setText("jLabel10");
        date2.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(153, 153, 153)));

        date3.setForeground(new java.awt.Color(255, 255, 255));
        date3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        date3.setText("jLabel18");
        date3.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(153, 153, 153)));

        date4.setForeground(new java.awt.Color(255, 255, 255));
        date4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        date4.setText("jLabel19");
        date4.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(153, 153, 153)));

        date5.setForeground(new java.awt.Color(255, 255, 255));
        date5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        date5.setText("jLabel20");
        date5.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(153, 153, 153)));

        date6.setForeground(new java.awt.Color(255, 255, 255));
        date6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        date6.setText("jLabel21");
        date6.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(153, 153, 153)));

        jTextField2.setBackground(new java.awt.Color(102, 102, 102));
        jTextField2.setFont(new java.awt.Font("Traditional Arabic", 1, 16)); // NOI18N
        jTextField2.setForeground(new java.awt.Color(255, 255, 255));
        jTextField2.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jTextField3.setBackground(new java.awt.Color(102, 102, 102));
        jTextField3.setFont(new java.awt.Font("Traditional Arabic", 1, 16)); // NOI18N
        jTextField3.setForeground(new java.awt.Color(255, 255, 255));
        jTextField3.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jTextField4.setBackground(new java.awt.Color(102, 102, 102));
        jTextField4.setFont(new java.awt.Font("Traditional Arabic", 1, 16)); // NOI18N
        jTextField4.setForeground(new java.awt.Color(255, 255, 255));
        jTextField4.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField4ActionPerformed(evt);
            }
        });

        jTextField5.setBackground(new java.awt.Color(102, 102, 102));
        jTextField5.setFont(new java.awt.Font("Traditional Arabic", 1, 16)); // NOI18N
        jTextField5.setForeground(new java.awt.Color(255, 255, 255));
        jTextField5.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField5ActionPerformed(evt);
            }
        });

        jTextField6.setBackground(new java.awt.Color(102, 102, 102));
        jTextField6.setFont(new java.awt.Font("Traditional Arabic", 1, 16)); // NOI18N
        jTextField6.setForeground(new java.awt.Color(255, 255, 255));
        jTextField6.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 211, Short.MAX_VALUE))
                .addGap(4, 4, 4)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 6, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField6, javax.swing.GroupLayout.DEFAULT_SIZE, 374, Short.MAX_VALUE)
                    .addComponent(jTextField5)
                    .addComponent(jTextField4)
                    .addComponent(jTextField1)
                    .addComponent(jTextField2)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTextField3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 4, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(date1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(date2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 144, Short.MAX_VALUE)
                    .addComponent(date3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(date4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(date5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(date6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 4, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane1)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel3Layout.createSequentialGroup()
                                                .addGap(10, 10, 10)
                                                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(jPanel3Layout.createSequentialGroup()
                                                .addGap(3, 3, 3)
                                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGap(0, 0, Short.MAX_VALUE))))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(15, 15, 15)
                                .addComponent(date1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(date2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(date3, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(date4, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(date5, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(date6, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 26, Short.MAX_VALUE)))))
                .addContainerGap())
        );

        getContentPane().add(jPanel3);
        jPanel3.setBounds(20, 220, 930, 390);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void CheckBox3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CheckBox3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CheckBox3ActionPerformed

    private void CheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CheckBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CheckBox1ActionPerformed

    private void jCheckBox27ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox27ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox27ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        
      
        if(jTextArea1.getText().trim().isEmpty()){
        
       String result1 = "";
        for(Component c: jPanel1.getComponents()){
        if(c.getClass().equals(JCheckBox.class)){
        JCheckBox jck = (JCheckBox)c;
        if(jck.isSelected()){
        result1 += jck.getText()+":\n";
        a++;
        
        }
        
        } 
            
        jTextArea1.setText(result1);
        
        }
jTextArea1.setText("");
if(CheckBox1.isSelected()){
jTextArea1.setText(jTextArea1.getText()+"فک بالا سمت را دندان شماره : 1\n");
} if(CheckBox2.isSelected()){jTextArea1.setText(jTextArea1.getText()+"فک بالا سمت راست دندان شماره : 2\n");
}
if(CheckBox3.isSelected()){jTextArea1.setText(jTextArea1.getText()+"فک بالا سمت راست دندان شماره : 3\n");
}
 if(CheckBox4.isSelected()){jTextArea1.setText(jTextArea1.getText()+"فک بالا سمت راست دندان شماره : 4\n");
 }
if(CheckBox5.isSelected()){jTextArea1.setText(jTextArea1.getText()+"فک بالا سمت راست دندان شماره : 5\n");
}
 if(CheckBox6.isSelected()){jTextArea1.setText(jTextArea1.getText()+"فک بالا سمت راست دندان شماره : 6\n");
 }
 if(CheckBox7.isSelected()){jTextArea1.setText(jTextArea1.getText()+"فک بالا سمت راست دندان شماره : 7\n");
 }
 if(CheckBox8.isSelected()){jTextArea1.setText(jTextArea1.getText()+"فک بالا سمت راست دندان شماره : 8\n");
 }
 if(jCheckBox9.isSelected()){jTextArea1.setText(jTextArea1.getText()+"فک پایین سمت راست دندان شماره : 1\n");
 }
 if(jCheckBox10.isSelected()){jTextArea1.setText(jTextArea1.getText()+"فک پایین سمت راست دندان شماره : 2\n");
 }
 if(jCheckBox11.isSelected()){jTextArea1.setText(jTextArea1.getText()+"فک پایین سمت راست دندان شماره : 3\n");
 }
 if(jCheckBox12.isSelected()){jTextArea1.setText(jTextArea1.getText()+"فک پایین سمت راست دندان شماره : 4\n");
 }
 if(jCheckBox13.isSelected()){jTextArea1.setText(jTextArea1.getText()+"فک پایین سمت راست دندان شماره : 5\n");
 }
 if(jCheckBox14.isSelected()){jTextArea1.setText(jTextArea1.getText()+"فک پایین سمت راست دندان شماره : 6\n");
 }
 if(jCheckBox15.isSelected()){jTextArea1.setText(jTextArea1.getText()+"فک پایین سمت راست دندان شماره : 7\n");
 }
 if(jCheckBox16.isSelected()){jTextArea1.setText(jTextArea1.getText()+"فک پایین سمت راست دندان شماره : 8\n");
 }
 
 
 if(jCheckBox17a.isSelected()){jTextArea1.setText(jTextArea1.getText()+"فک بالا سمت چپ دندان شماره : 1\n");}
 if(jCheckBox18b.isSelected()){jTextArea1.setText(jTextArea1.getText()+"فک بالا سمت چپ دندان شماره : 2\n");}
 if(jCheckBox20c.isSelected()){jTextArea1.setText(jTextArea1.getText()+"فک بالا سمت چپ دندان شماره : 3\n");}
 if(jCheckBox23d.isSelected()){jTextArea1.setText(jTextArea1.getText()+"فک بالا سمت چپ دندان شماره : 4\n");}
 if(jCheckBox19e.isSelected()){jTextArea1.setText(jTextArea1.getText()+"فک بالا سمت چپ دندان شماره : 5\n");}
 if(jCheckBox21f.isSelected()){jTextArea1.setText(jTextArea1.getText()+"فک بالا سمت چپ دندان شماره : 6\n");}
 if(jCheckBox22g.isSelected()){jTextArea1.setText(jTextArea1.getText()+"فک بالا سمت چپ دندان شماره : 7\n");}
 if(jCheckBox24h.isSelected()){jTextArea1.setText(jTextArea1.getText()+"فک بالا سمت چپ دندان شماره : 8\n");}
 if(jCheckBox25.isSelected()){jTextArea1.setText(jTextArea1.getText()+"فک پایین سمت چپ دندان شماره : 1\n");}
 if(jCheckBox26.isSelected()){jTextArea1.setText(jTextArea1.getText()+"فک پایین سمت چپ دندان شماره : 2\n");}
 if(jCheckBox27.isSelected()){jTextArea1.setText(jTextArea1.getText()+"فک پایین سمت چپ دندان شماره : 3\n");}
 if(jCheckBox28.isSelected()){jTextArea1.setText(jTextArea1.getText()+"فک پایین سمت چپ دندان شماره : 4\n");}
 if(jCheckBox29.isSelected()){jTextArea1.setText(jTextArea1.getText()+"فک پایین سمت چپ دندان شماره : 5\n");}
 if(jCheckBox30.isSelected()){jTextArea1.setText(jTextArea1.getText()+"فک پایین سمت چپ دندان شماره : 6\n");}
 if(jCheckBox31.isSelected()){jTextArea1.setText(jTextArea1.getText()+"فک پایین سمت چپ دندان شماره : 7\n");}
 if(jCheckBox32.isSelected()){jTextArea1.setText(jTextArea1.getText()+"فک پایین سمت چپ دندان شماره : 8\n");}
 
        
        }
        else{
        
        
            if(CheckBox1.isSelected()){
jTextArea1.setText(jTextArea1.getText()+"فک بالا سمت راست دندان شماره : 1\n");

} if(CheckBox2.isSelected()){jTextArea1.setText(jTextArea1.getText()+"فک بالا سمت راست دندان شماره : 2\n");}
if(CheckBox3.isSelected()){jTextArea1.setText(jTextArea1.getText()+"فک بالا سمت راست دندان شماره : 3\n");}
 if(CheckBox4.isSelected()){jTextArea1.setText(jTextArea1.getText()+"فک بالا سمت راست دندان شماره : 4\n");}
if(CheckBox5.isSelected()){jTextArea1.setText(jTextArea1.getText()+"فک بالا سمت راست دندان شماره : 5\n");}
 if(CheckBox6.isSelected()){jTextArea1.setText(jTextArea1.getText()+"فک بالا سمت راست دندان شماره : 6\n");}
 if(CheckBox7.isSelected()){jTextArea1.setText(jTextArea1.getText()+"فک بالا سمت راست دندان شماره : 7\n");}
 if(CheckBox8.isSelected()){jTextArea1.setText(jTextArea1.getText()+"فک بالا سمت راست دندان شماره : 8\n");}
 if(jCheckBox9.isSelected()){jTextArea1.setText(jTextArea1.getText()+"فک پایین سمت راست دندان شماره : 1\n");}
 if(jCheckBox10.isSelected()){jTextArea1.setText(jTextArea1.getText()+"فک پایین سمت راست دندان شماره : 2\n");}
 if(jCheckBox11.isSelected()){jTextArea1.setText(jTextArea1.getText()+"فک پایین سمت راست دندان شماره : 3\n");}
 if(jCheckBox12.isSelected()){jTextArea1.setText(jTextArea1.getText()+"فک پایین سمت راست دندان شماره : 4\n");}
 if(jCheckBox13.isSelected()){jTextArea1.setText(jTextArea1.getText()+"فک پایین سمت راست دندان شماره : 5\n");}
 if(jCheckBox14.isSelected()){jTextArea1.setText(jTextArea1.getText()+"فک پایین سمت راست دندان شماره : 6\n");}
 if(jCheckBox15.isSelected()){jTextArea1.setText(jTextArea1.getText()+"فک پایین سمت راست دندان شماره : 7\n");}
 if(jCheckBox16.isSelected()){jTextArea1.setText(jTextArea1.getText()+"فک پایین سمت راست دندان شماره : 8\n");}
 
 
 if(jCheckBox17a.isSelected()){jTextArea1.setText(jTextArea1.getText()+"فک بالا سمت چپ دندان شماره : 1\n");}
 if(jCheckBox18b.isSelected()){jTextArea1.setText(jTextArea1.getText()+"فک بالا سمت چپ دندان شماره : 2\n");}
 if(jCheckBox20c.isSelected()){jTextArea1.setText(jTextArea1.getText()+"فک بالا سمت چپ دندان شماره : 3\n");}
 if(jCheckBox23d.isSelected()){jTextArea1.setText(jTextArea1.getText()+"فک بالا سمت چپ دندان شماره : 4\n");}
 if(jCheckBox19e.isSelected()){jTextArea1.setText(jTextArea1.getText()+"فک بالا سمت چپ دندان شماره : 5\n");}
 if(jCheckBox21f.isSelected()){jTextArea1.setText(jTextArea1.getText()+"فک بالا سمت چپ دندان شماره : 6\n");}
 if(jCheckBox22g.isSelected()){jTextArea1.setText(jTextArea1.getText()+"فک بالا سمت چپ دندان شماره : 7\n");}
 if(jCheckBox24h.isSelected()){jTextArea1.setText(jTextArea1.getText()+"فک بالا سمت چپ دندان شماره : 8\n");}
 if(jCheckBox25.isSelected()){jTextArea1.setText(jTextArea1.getText()+"فک پایین سمت چپ دندان شماره : 1\n");}
 if(jCheckBox26.isSelected()){jTextArea1.setText(jTextArea1.getText()+"فک پایین سمت چپ دندان شماره : 2\n");}
 if(jCheckBox27.isSelected()){jTextArea1.setText(jTextArea1.getText()+"فک پایین سمت چپ دندان شماره : 3\n");}
 if(jCheckBox28.isSelected()){jTextArea1.setText(jTextArea1.getText()+"فک پایین سمت چپ دندان شماره : 4\n");}
 if(jCheckBox29.isSelected()){jTextArea1.setText(jTextArea1.getText()+"فک پایین سمت چپ دندان شماره : 5\n");}
 if(jCheckBox30.isSelected()){jTextArea1.setText(jTextArea1.getText()+"فک پایین سمت چپ دندان شماره : 6\n");}
 if(jCheckBox31.isSelected()){jTextArea1.setText(jTextArea1.getText()+"فک پایین سمت چپ دندان شماره : 7\n");}
 if(jCheckBox32.isSelected()){jTextArea1.setText(jTextArea1.getText()+"فک پایین سمت چپ دندان شماره : 8\n");}
 
        
        }
         
 

        
        
        
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jCheckBox26ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox26ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox26ActionPerformed

    private void jCheckBox28ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox28ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox28ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       
        int num = JOptionPane.showOptionDialog(null, "معلومات ذخیره گردد!!", "پیام تاییدی", JOptionPane.OK_CANCEL_OPTION, JOptionPane.QUESTION_MESSAGE, null, null, null);
                  
                    if(num == 0){
                       if(jTextField1.getText().trim().isEmpty()||jTextArea1.getText().trim().isEmpty()
                          ){
                       
                           JOptionPane.showMessageDialog(null, "لطفا تمام مشخصات مریض را وارد کنید","هشدار",JOptionPane.OK_OPTION);
                       
                       } else{
                        try {
            Class.forName("org.h2.Driver");
            
//            String query = "insert into "+Constances.TableNames.TOOTH_DETAILS+"(date_1,description_1,teeth_location,teeth_num) values('"
//                    +date1.getText()+"','"+jTextField1.getText()+"','"+
//                    jTextArea1.getText()+"','"+a+"')";
            
             String query = "update "+Constances.TableNames.TOOTH_DETAILS+" set "+Constances.TeethInfo.DATE1+" = '"+date1.getText()
                           +" ',"+Constances.TeethInfo.DESCRIPTION1+" = '"+jTextField1.getText()+"',"+Constances.TeethInfo.TEETH_LOCATION+" = '"+jTextArea1.getText()+"',"                     
                     +Constances.TeethInfo.DATE2+" = '"+date2.getText()
                           +" ',"+Constances.TeethInfo.DESCRIPTION2+" = '"+jTextField2.getText()+"',"+
                     Constances.TeethInfo.DATE3+" = '"+date3.getText()
                           +" ',"+Constances.TeethInfo.DESCRIPTION3+" = '"+jTextField3.getText()+"',"+                   
                     Constances.TeethInfo.DATE4+" = '"+date4.getText()
                           +" ',"+Constances.TeethInfo.DESCRIPTION4+" = '"+jTextField4.getText()+"',"+                    
                     Constances.TeethInfo.DATE5+" = '"+date5.getText()
                           +" ',"+Constances.TeethInfo.DESCRIPTION5+" = '"+jTextField5.getText()+"',"+                   
                     Constances.TeethInfo.DATE6+" = '"+date6.getText()
                           +" ',"+Constances.TeethInfo.DESCRIPTION6+" = '"+jTextField6.getText()+"',"+Constances.TeethInfo.TEETH_NUM
                           +" ='"+a+"' where "+Constances.TeethInfo.ID_NUM+" = '"+jTextField8.getText()+"'";
                            
            
            
            Connection con = DriverManager.getConnection("jdbc:h2:~/dintest","jawad","1234");
            if(con!=null){
                Statement st = con.createStatement();
                int result =st.executeUpdate(query);
                
                if(result != 0){
                    JOptionPane.showMessageDialog(null, "مشخصات مریض ذخیره گردید!!","",JOptionPane.INFORMATION_MESSAGE);
                   jTextField1.setText("");
                   jTextField2.setText("");
                   jTextField3.setText("");
                   jTextField4.setText("");
                   jTextField5.setText("");
                   jTextField6.setText("");
                   jTextArea1.setText("");
                   a=0;
                   dm.disp();
                  
                }else{
                JOptionPane.showMessageDialog(null, "نمبر مشخصه مریض نامعتبر!!","",JOptionPane.WARNING_MESSAGE);
                }
            }
            
            
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Demo.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(Demo.class.getName()).log(Level.SEVERE, null, ex);
        } 
                       }       
                    }  
                else{
                JOptionPane.showMessageDialog(null,"معلومات ذخیره نگردید!!","",JOptionPane.WARNING_MESSAGE);
                }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextField8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField8MouseClicked
        jTextField8.setEditable(true);
        jTextField8.setText("");
         
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField8MouseClicked

    private void jTextField8KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField8KeyPressed
   if(evt.getKeyCode()==KeyEvent.VK_ENTER){
   
    int aa = 0;
          int num=0;
        String pId ="";
        try{
        personId = jTextField8.getText();
            
        
        if(jTextField8.getText().trim().isEmpty()){
  JOptionPane.showMessageDialog(null, "لطفا نمبر مشخصه مریض را وارد کنید","پیام تاییدی",JOptionPane.INFORMATION_MESSAGE);
  }else{
        String query ="select * from "+Constances.TableNames.TOOTH_DETAILS+" where "+Constances.TeethInfo.ID_NUM+" = '"+personId+"'";
        try {
            Class.forName("org.h2.Driver");
            Connection con = DriverManager.getConnection("jdbc:h2:~/dintest", "jawad", "1234");
            if(con!=null){
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery(query);
            
                while(rs.next()){
                    pId=rs.getString(1);
                if(personId.equals(pId)){
                
             
                 date1.setText(rs.getString(3));
                 date2.setText(rs.getString(4));
                 date3.setText(rs.getString(5));
                 date4.setText(rs.getString(6));
                 date5.setText(rs.getString(7));
                 date6.setText(rs.getString(8));
                 
                 jTextField1.setText(rs.getString(9));
                 jTextField2.setText(rs.getString(10));
                 jTextField3.setText(rs.getString(11));
                 jTextField4.setText(rs.getString(12));
                 jTextField5.setText(rs.getString(13));
                 jTextField6.setText(rs.getString(14));
                 
                 jTextArea1.setText(jTextArea1.getText().concat(rs.getString(15)));
                 aa=Integer.parseInt(rs.getString(16));
                 
                 a = a+aa;
                }
                  else{
                JOptionPane.showMessageDialog(null, "نمبر مشخصه نامعتبر است!!","هشدار",JOptionPane.WARNING_MESSAGE);
                
                } 
                
                }
      
      
  }
        } catch (ClassNotFoundException ex) {
          Logger.getLogger(Demo.class.getName()).log(Level.SEVERE, null, ex);
      } catch (SQLException ex) {
          Logger.getLogger(Demo.class.getName()).log(Level.SEVERE, null, ex);
      }
        
  }
        
        }catch(NullPointerException np){}
        
        
   
   }
    }//GEN-LAST:event_jTextField8KeyPressed

    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField4ActionPerformed

    private void jTextField5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField5ActionPerformed
public void loadInfo(){
 String personId = jTextField8.getText();
       String query ="select * from "+Constances.TableNames.SickDetails+" where "+Constances.SickDetails.Number+" = '"+personId+"'";
        
        try {
            Class.forName("org.h2.Driver");
            Connection con = DriverManager.getConnection("jdbc:h2:~/dintest", "jawad", "1234");
            if(con!=null){
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery(query);
            
                while(rs.next()){
             jTextField1.setText(rs.getString(2));
             jTextField2.setText(rs.getString(3));
             jTextField3.setText(rs.getString(4));
             jTextField4.setText(rs.getString(6));
             jTextField5.setText(rs.getString(16));
             jTextField6.setText(rs.getString(7));
//             detailsPrice.setText(rs.getString(9));
//             detailsFirst.setText(rs.getString(10));
//             detailsSecond.setText(rs.getString(11));
//             detailsThird.setText(rs.getString(12));
//             detailsFourth.setText(rs.getString(17));
//             detailsRemain.setText(rs.getString(13));
//             ShamsiDate sd = new ShamsiDate();
//             date1.setText(sd.getCurrentShamsidate());
//             detailsSick.setText(rs.getString(8));
                    
                 
                }
             
  }
        } catch (ClassNotFoundException ex) {
          Logger.getLogger(Demo.class.getName()).log(Level.SEVERE, null, ex);
      } catch (SQLException ex) {
          Logger.getLogger(Demo.class.getName()).log(Level.SEVERE, null, ex);
      }




}
    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox CheckBox1;
    private javax.swing.JCheckBox CheckBox2;
    private javax.swing.JCheckBox CheckBox3;
    private javax.swing.JCheckBox CheckBox4;
    private javax.swing.JCheckBox CheckBox5;
    private javax.swing.JCheckBox CheckBox6;
    private javax.swing.JCheckBox CheckBox7;
    private javax.swing.JCheckBox CheckBox8;
    private javax.swing.JLabel date1;
    private javax.swing.JLabel date2;
    private javax.swing.JLabel date3;
    private javax.swing.JLabel date4;
    private javax.swing.JLabel date5;
    private javax.swing.JLabel date6;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JCheckBox jCheckBox10;
    private javax.swing.JCheckBox jCheckBox11;
    private javax.swing.JCheckBox jCheckBox12;
    private javax.swing.JCheckBox jCheckBox13;
    private javax.swing.JCheckBox jCheckBox14;
    private javax.swing.JCheckBox jCheckBox15;
    private javax.swing.JCheckBox jCheckBox16;
    private javax.swing.JCheckBox jCheckBox17a;
    private javax.swing.JCheckBox jCheckBox18b;
    private javax.swing.JCheckBox jCheckBox19e;
    private javax.swing.JCheckBox jCheckBox20c;
    private javax.swing.JCheckBox jCheckBox21f;
    private javax.swing.JCheckBox jCheckBox22g;
    private javax.swing.JCheckBox jCheckBox23d;
    private javax.swing.JCheckBox jCheckBox24h;
    private javax.swing.JCheckBox jCheckBox25;
    private javax.swing.JCheckBox jCheckBox26;
    private javax.swing.JCheckBox jCheckBox27;
    private javax.swing.JCheckBox jCheckBox28;
    private javax.swing.JCheckBox jCheckBox29;
    private javax.swing.JCheckBox jCheckBox30;
    private javax.swing.JCheckBox jCheckBox31;
    private javax.swing.JCheckBox jCheckBox32;
    private javax.swing.JCheckBox jCheckBox9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField8;
    // End of variables declaration//GEN-END:variables
}
